// =============================================================================
// Component Name: LabManual
// Description:    Educational Lab Guide & Textbook Workbook for VLSI coursework.
//                 Outlines synchronous clocking policies, input metastability DFFs,
//                 multiplex scanning math, and Yosys compilation statistics.
// =============================================================================

import React, { useState } from 'react';
import { BookOpen, AlertOctagon, HelpCircle, FileCheck, Landmark, ShieldCheck } from 'lucide-react';

interface LabManualProps {}

export const LabManual: React.FC<LabManualProps> = () => {
  const [activeTab, setActiveTab] = useState<string>('gated_clocks');

  const topics = [
    {
      id: "gated_clocks",
      title: "1. Synchronous Clock Timing Chains",
      icon: BookOpen,
      content: (
        <div className="flex flex-col gap-4 text-slate-300 font-sans text-xs md:text-sm">
          <div className="flex items-center gap-2 text-digital-green border-b border-white/5 pb-2">
            <ShieldCheck className="w-4 h-4" />
            <h4 className="font-display font-bold text-white text-sm">Synchronous Clocking and Clock Enables</h4>
          </div>
          
          <p className="leading-relaxed text-slate-400 text-[13px]">
            In digital VLSI and FPGA design, **Gated Clocks** (using counters or logic gates to directly drive the clock pin of another flip-flop) are **strictly forbidden** (unlicensed for industrial synthesis). 
            Doing so introduces significant clock skew, breaks routing trees (Clock Trees), and causes severe clock domain crossing violations (metastability).
          </p>

          <div className="bg-red-950/20 border border-red-800/40 rounded-lg p-3 flex gap-2.5 items-start text-xs text-red-200">
            <AlertOctagon className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div>
              <strong className="font-bold text-red-300">Bad Design Pattern (Clock Dividers):</strong>
              <pre className="font-mono text-[10px] text-red-400 bg-red-950/50 p-2 rounded mt-2 overflow-x-auto leading-normal">
{`// ❌ NEVER DO THIS on FPGA or ASIC!
always @(posedge clk) begin
    if (counter == MAX) slow_clk <= ~slow_clk; // Clock source toggle
end
always @(posedge slow_clk) begin // Gated clock pin! Skew & Timing failure.
    seconds <= seconds + 1;
end`}
              </pre>
              <p className="mt-1 text-[11px] text-slate-400">
                Because <code className="text-white">slow_clk</code> passes through standard logic routing rather than low-skew clock buffers (BUFG), its rising edge arrives at different registers at different times, violating setup and hold timing.
              </p>
            </div>
          </div>

          <div className="bg-emerald-950/20 border border-emerald-900/40 rounded-lg p-3 flex gap-2.5 items-start text-xs text-emerald-200">
            <FileCheck className="w-5 h-5 text-digital-green flex-shrink-0 mt-0.5" />
            <div>
              <strong className="font-bold text-emerald-300">Correct Design Pattern (Clock Enables):</strong>
              <p className="mt-1 leading-relaxed text-slate-300">
                Instead of dividing the clock, distribute the unified high-speed board clock (<code className="text-white font-mono">clk</code>) to **every** register in the system. Use a single-cycle **enable pulse** generated by a divider to license updates.
              </p>
              <pre className="font-mono text-[10px] text-emerald-400 bg-emerald-950/50 p-2 rounded mt-2 overflow-x-auto leading-normal">
{`// ✅ HIGH VLSI RELIABILITY WAY
always @(posedge clk) begin
    if (divider == MAX-1) begin
         divider <= 0;
         one_sec_tick <= 1'b1; // Pulse high for EXACTLY one clock period
    end else begin
         one_sec_tick <= 1'b0;
    end
end
always @(posedge clk) begin // Everything remains synced to master clock!
    if (one_sec_tick) begin // Licenced enable check
         seconds <= (seconds == 59) ? 0 : seconds + 1;
    end
end`}
              </pre>
            </div>
          </div>
        </div>
      )
    },
    {
      id: "metastability",
      title: "2. Metastability & Input D-FFs",
      icon: AlertOctagon,
      content: (
        <div className="flex flex-col gap-4 text-slate-300 font-sans text-xs md:text-sm">
          <div className="flex items-center gap-2 text-digital-green border-b border-white/5 pb-2">
            <ShieldCheck className="w-4 h-4" />
            <h4 className="font-display font-bold text-white text-sm">Metastability in Asynchronous Inputs</h4>
          </div>

          <p className="leading-relaxed text-slate-400 text-[13px]">
            When an external button is pressed, it is strictly asynchronous to the internal 50MHz FPGA clock. If the button slides from low to high during the **setup** or **hold** window of the input flip-flop, the internal cell can log an indeterminate logic value (neither 0 nor 1), oscillating and entering a **metastable state**.
          </p>

          <div className="p-3 bg-slate-900 border border-white/5 rounded-lg flex flex-col gap-2">
            <span className="font-mono text-xs text-digital-amber font-semibold">THE TWO-STAGE SYNC TO RESCUE:</span>
            <p className="text-slate-400 text-xs">
              By cascade-routing the input pin through two sequential D-Flip-Flops clocked by the master clock, the probability of metastability propagating into the internal FSM drops near zero, exponentially increasing the <strong className="text-white">Mean Time Between Failures (MTBF)</strong>.
            </p>
            
            {/* Visual ascii chain */}
            <pre className="font-mono text-[9px] md:text-xs text-slate-400 bg-black/60 p-3 rounded text-center border border-white/5 leading-tight">
{`ASYNC PIN   +--------+      SYNC_1    +--------+      SYNC_2 (SAFE)
----------->|  D  Q  |--------------->|  D  Q  |---------------> INTERNAL LOGIC
            |        |                |        |
    CLK --->|  >     |        CLK --->|  >     |
            +--------+                +--------+`}
            </pre>
          </div>

          <div className="p-3 bg-slate-900 border border-white/5 rounded-lg flex flex-col gap-2">
            <span className="font-mono text-xs text-slate-300 font-semibold">Integrator Button Debouncing:</span>
            <p className="text-slate-400 text-xs leading-normal">
              Physical button keycaps have metallic spring contacts. When clicked, they mechanically bounce between states for up to 10-20 milliseconds. Our Verilog code applies a saturated digital register counter that requires the input to stay stable for e.g. <code className="text-white font-mono">DEBOUNCE_COUNTS</code> before propagating the stable signal, effectively locking out sub-millisecond mechanical chatter.
            </p>
          </div>
        </div>
      )
    },
    {
      id: "multiplexing",
      title: "3. 7-Segment Multiplex Principles",
      icon: HelpCircle,
      content: (
        <div className="flex flex-col gap-4 text-slate-300 font-sans text-xs md:text-sm">
          <div className="flex items-center gap-2 text-digital-green border-b border-white/5 pb-2">
            <ShieldCheck className="w-4 h-4" />
            <h4 className="font-display font-bold text-white text-sm">Persistence of Vision (POV) Multiplexing</h4>
          </div>

          <p className="leading-relaxed text-slate-400 text-[13px]">
            If we wanted to drive 6 7-segment displays statically, we would need:
            <br />
            <code className="text-white font-mono">(6 digits * 7 cathodes) + 6 decimal points + 6 anodes = 48 FPGA pins!</code>
            <br />
            No compact FPGA has this massive number of devoted physical pins for simple readouts.
          </p>

          <div className="p-3.5 bg-slate-900 border border-white/5 rounded-lg flex flex-col gap-2 text-xs">
            <strong className="text-[12px] text-digital-blue font-mono uppercase">The Pin-Sharing Technique:</strong>
            <p className="text-slate-400">
               Instead, we tie all matching cathode lines (segment pins A-G) of the 6 digits together onto a single 7-bit bus (<code className="text-white font-bold">seg[6:0]</code>). We then turn on **only one digit** at a time by pulling its specific common anode pin low (<code className="text-white font-bold">an[5:0]</code> = active low).
            </p>
            <ul className="list-disc pl-4 text-slate-300 flex flex-col gap-1 my-1">
              <li>By cycling through digits 5 to 0 at a high frequency (e.g. 1kHz refresh rate), each digit lights up for exactly <strong>1.67 milliseconds</strong>.</li>
              <li>Because of the human eye's **Persistence of Vision (POV)**, the rapid flashing is invisible, and all 6 digits appear to glow steadily at the same time!</li>
            </ul>
          </div>

          {/* Table mappings */}
          <div className="border border-white/5 rounded-lg overflow-hidden font-mono text-[10px]" id="anode_matrix_table">
            <div className="bg-slate-950 p-2 font-bold flex justify-between border-b border-white/5">
              <span>SCAN STATE</span>
              <span>AN_BUS SELECT [5:0]</span>
              <span>ACTIVE DIGIT</span>
            </div>
            {[
              { scan: "STATE 5", bus: "6'b011111", digit: "Hours Tens (Leftmost)" },
              { scan: "STATE 4", bus: "6'b101111", digit: "Hours Ones" },
              { scan: "STATE 3", bus: "6'b110111", digit: "Minutes Tens" },
              { scan: "STATE 2", bus: "6'b111011", digit: "Minutes Ones" },
              { scan: "STATE 1", bus: "6'b111101", digit: "Seconds Tens" },
              { scan: "STATE 0", bus: "6'b111110", digit: "Seconds Ones (Rightmost)" }
            ].map(row => (
              <div key={row.scan} className="p-2 flex justify-between border-b border-white/2 hover:bg-white/1 group">
                <span className="text-slate-400 group-hover:text-digital-green transition-colors">{row.scan}</span>
                <span className="text-digital-blue font-bold">{row.bus}</span>
                <span className="text-slate-300">{row.digit}</span>
              </div>
            ))}
          </div>
        </div>
      )
    },
    {
      id: "netlist_theory",
      title: "4. RTL-to-Gate Synthesis Theory",
      icon: Landmark,
      content: (
        <div className="flex flex-col gap-4 text-slate-300 font-sans text-xs md:text-sm">
          <div className="flex items-center gap-2 text-digital-green border-b border-white/5 pb-2">
            <ShieldCheck className="w-4 h-4" />
            <h4 className="font-display font-bold text-white text-sm">Logic Mapping of Behavioral Verilog</h4>
          </div>

          <p className="leading-relaxed text-slate-400 text-[13px]">
            The synthesis tool (like **Yosys** or **Vivado Synthesis**) parses behavioral Verilog structures and converts them to binary logic structures. When Yosys runs your <code className="text-white font-mono">synthesis.ys</code>, it performs three primary conversion transformations:
          </p>

          <ol className="list-decimal pl-4 text-xs text-slate-300 flex flex-col gap-3">
            <li>
              <strong className="text-slate-200">Procedure Parsing (<code className="text-white font-mono">proc</code>):</strong>
              <p className="text-slate-400 mt-0.5">
                Translates <code className="text-white font-mono">always @(posedge clk)</code> blocks. If a register is assigned inside a posedge clock procedural block, the synthesizer instantiates standard hardware D-Flip-Flops connected clock-wise.
              </p>
            </li>
            <li>
              <strong className="text-slate-200">FSM Mapping (<code className="text-white font-mono">fsm</code>):</strong>
              <p className="text-slate-400 mt-0.5">
                Automatically identifies the modes' state machine variables (<code className="text-white font-mono">current_state</code>) and optimizes state encoding (e.g., converting the 3-bit binary states sequence into One-Hot signals) to limit combinational logic depth and increase maximum speed.
              </p>
            </li>
            <li>
              <strong className="text-slate-200">Technology Mapping (<code className="text-white font-mono">techmap / abc</code>):</strong>
              <p className="text-slate-400 mt-0.5">
                Translates mathematical equations (e.g. division <code className="text-white font-mono">/ 10</code>, modulo <code className="text-white font-mono">% 10</code>, addition <code className="text-white font-mono">+ 1</code>) into gate netlists (Adders, Multiplexers, and LUT gates standard cells) provided in the library catalog.
              </p>
            </li>
          </ol>

          <div className="p-3 bg-slate-900 border border-white/5 rounded-lg flex flex-col gap-2 font-mono text-[10.5px]">
            <span className="text-digital-amber">YOSYS SYNTHESIS RESULTS (ESTIMATED):</span>
            <div className="grid grid-cols-2 gap-2 text-slate-400">
              <span>- Standard Registers (DFFs): <strong>78 cells</strong></span>
              <span>- 6-input LUTs (Look up tables): <strong>142 cells</strong></span>
              <span>- BUFG Clock Buffers: <strong>1 cell</strong></span>
              <span>- Total Cell Gate Area estimate: <strong>322 units</strong></span>
            </div>
          </div>
        </div>
      )
    }
  ];

  const activeTopic = topics.find(t => t.id === activeTab) || topics[0];

  return (
    <div className="w-full bg-slate-950 border border-white/5 rounded-xl p-5 md:p-6 flex flex-col gap-5 relative overflow-hidden" id="lab_manual">
      
      {/* Header */}
      <div className="flex items-center gap-2 pb-3 border-b border-white/5">
        <BookOpen className="w-5 h-5 text-digital-green" />
        <h3 className="font-display font-bold text-white text-sm">VLSI Lab Manual & Course Workbook</h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-start">
        
        {/* Navigation Sidebar (left 4 columns) */}
        <div className="md:col-span-4 flex flex-col gap-2" id="sidebar_topics_container">
          {topics.map(topic => {
            const IconComp = topic.icon;
            const isSelected = activeTab === topic.id;
            return (
              <button
                key={topic.id}
                onClick={() => setActiveTab(topic.id)}
                className={`w-full text-left p-3.5 rounded-lg border transition-all cursor-pointer font-display text-xs font-semibold flex items-center gap-2.5 ${
                  isSelected
                    ? 'bg-digital-green/10 border-digital-green text-white font-bold'
                    : 'bg-slate-900/40 border-slate-850 text-slate-400 hover:border-slate-705 hover:bg-slate-900/60'
                }`}
                id={`topic_tab_${topic.id}`}
              >
                <IconComp className={`w-4 h-4 ${isSelected ? 'text-digital-green animate-pulse' : 'text-slate-500'}`} />
                <span>{topic.title}</span>
              </button>
            );
          })}
        </div>

        {/* Content Box (right 8 columns) */}
        <div className="md:col-span-8 bg-slate-900/20 border border-white/5 rounded-xl p-5 min-h-[300px]" id="manual_details_box">
          {activeTopic.content}
        </div>

      </div>

    </div>
  );
};
